import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  container: {
    fontFamily: "'Orbitron', sans-serif",
    height: '100dvh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#000000', // 완전한 검정 배경
    color: '#E6EDF3',
    position: 'relative',
    overflow: 'hidden',
    paddingTop: 'env(safe-area-inset-top)',
    paddingBottom: 'env(safe-area-inset-bottom)',
  },
  chatUIContainer: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: 'transparent',
  },
  avatarContainer: {
    padding: '20px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '120px',
    minHeight: '120px',
  },
  messageList: {
    flex: 1,
    overflowY: 'auto',
    padding: '10px',
    display: 'flex',
    flexDirection: 'column-reverse',
    WebkitOverflowScrolling: 'touch',
  },
  messageRow: {
    margin: '8px 0',
    maxWidth: '85%',
    display: 'flex',
    alignItems: 'flex-end',
  },
  myMessageRow: {
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
  },
  otherMessageRow: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
  },
  bubble: {
    padding: '12px 18px',
    borderRadius: '15px',
    backdropFilter: 'blur(5px)',
    borderStyle: 'solid',
    borderWidth: '1px',
  },
  myBubble: {
    backgroundColor: 'rgba(0, 122, 255, 0.2)',
    color: '#FFFFFF',
    borderColor: 'rgba(0, 122, 255, 0.6)',
    boxShadow: '0 0 15px rgba(0, 122, 255, 0.2)',
    borderBottomRightRadius: '5px',
  },
  otherBubble: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: '#E6EDF3',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderBottomLeftRadius: '5px',
  },
  timestamp: {
    fontSize: '10px',
    color: '#8B949E',
    margin: '0 8px',
    marginBottom: '5px',
    opacity: 0.7,
  },
  textMessage: {
    fontSize: '16px',
    lineHeight: '1.5',
    margin: 0,
    whiteSpace: 'pre-wrap',
  },
  imageMessage: {
    width: '250px',
    height: 'auto',
    aspectRatio: '3/4',
    objectFit: 'cover',
    borderRadius: '15px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
  },
  imageText: {
    marginTop: '8px',
    fontSize: '16px',
  },
  voiceContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '220px',
  },
  voiceButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '24px',
    marginRight: '10px',
    padding: 0,
    color: '#00D1FF',
  },
  voiceProgressBar: {
    flex: 1,
    height: '4px',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: '2px',
    position: 'relative',
  },
  voiceProgressDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#00D1FF',
    position: 'absolute',
    top: '-3px',
  },
  voiceDuration: {
    fontSize: '12px',
    marginLeft: '10px',
  },
  inputOuterContainer: {
    padding: '10px 15px',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderTop: '1px solid rgba(0, 209, 255, 0.3)',
    backdropFilter: 'blur(10px)',
    paddingBottom: 'calc(10px + env(safe-area-inset-bottom))',
  },
};
